USE master;
GO


CREATE DATABASE IF NOT EXISTS 'CrudWithILogger';
GO

USE 'CrudWithILogger';
GO


CREATE TABLE Users(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FullName NVARCHAR(50) NOT NULL,
    Age INT NOT NULL, 
    IsActive BIT DEFAULT 1
)
GO

CREATE TABLE Logs(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    UserId INT NULL FOREIGN KEY REFERENCES Users(Id),
    Action NVARCHAR(50) NOT NULL,
    Level NVARCHAR(20) NOT NULL,
    Timestamp DATETIME DEFAULT GETDATE()
)
